property:
  property1: This is a test property1!

spring:
  datasource:
    url: jdbc:mysql://192.168.1.110:3306/maize
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    static-path-pattern: /static/**
  redis:
    host: 192.168.1.110
    port: 6379
    database: 0
server:
  port: 8080
